"""Add additional fields to User model

Revision ID: 25fd83c12548
Revises: a6ba66e797a1
Create Date: 2024-07-28 17:50:12.665482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fd83c12548'
down_revision = 'a6ba66e797a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ethnicity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('religion', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cccd', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cccd')
        batch_op.drop_column('gender')
        batch_op.drop_column('religion')
        batch_op.drop_column('ethnicity')

    # ### end Alembic commands ###
